export const countries = [
    { label: "Afeganistão", value: "Afeganistao" },
    { label: "África do Sul", value: "Africa do Sul" },
    { label: "Albânia", value: "Albania" },
    { label: "Alemanha", value: "Alemanha" },
    { label: "Andorra", value: "Andorra" },
    { label: "Angola", value: "Angola" },
    { label: "Antígua e Barbuda", value: "Antigua e Barbuda" },
    { label: "Arábia Saudita", value: "Arabia Saudita" },
    { label: "Argélia", value: "Argelia" },
    { label: "Argentina", value: "Argentina" },
    { label: "Armênia", value: "Armenia" },
    { label: "Austrália", value: "Australia" },
    { label: "Áustria", value: "Austria" },
    { label: "Azerbaijão", value: "Azerbaijao" },
    { label: "Bahamas", value: "Bahamas" },
    { label: "Bahrein", value: "Bahrein" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Barbados", value: "Barbados" },
    { label: "Bélgica", value: "Belgica" },
    { label: "Belize", value: "Belize" },
    { label: "Benin", value: "Benin" },
    { label: "Bielorrússia", value: "Bielorrussia" },
    { label: "Bolívia", value: "Bolivia" },
    { label: "Bósnia e Herzegovina", value: "Bosnia e Herzegovina" },
    { label: "Botsuana", value: "Botsuana" },
    { label: "Brasil", value: "Brasil" },
    { label: "Brunei", value: "Brunei" },
    { label: "Bulgária", value: "Bulgaria" },
    { label: "Burkina Faso", value: "Burkina Faso" },
    { label: "Burundi", value: "Burundi" },
    { label: "Butão", value: "Butao" },
    { label: "Cabo Verde", value: "Cabo Verde" },
    { label: "Camarões", value: "Camaroes" },
    { label: "Camboja", value: "Camboja" },
    { label: "Canadá", value: "Canada" },
    { label: "Catar", value: "Catar" },
    { label: "Cazaquistão", value: "Cazaquistao" },
    { label: "Chade", value: "Chade" },
    { label: "Chile", value: "Chile" },
    { label: "China", value: "China" },
    { label: "Chipre", value: "Chipre" },
    { label: "Colômbia", value: "Colombia" },
    { label: "Comores", value: "Comores" },
    { label: "Congo (Brazzaville)", value: "Congo (Brazzaville)" },
    { label: "Congo (Kinshasa)", value: "Congo (Kinshasa)" },
    { label: "Coreia do Norte", value: "Coreia do Norte" },
    { label: "Coreia do Sul", value: "Coreia do Sul" },
    { label: "Costa do Marfim", value: "Costa do Marfim" },
    { label: "Costa Rica", value: "Costa Rica" },
    { label: "Croácia", value: "Croacia" },
    { label: "Cuba", value: "Cuba" },
    { label: "Dinamarca", value: "Dinamarca" },
    { label: "Djibouti", value: "Djibouti" },
    { label: "Dominica", value: "Dominica" },
    { label: "Egito", value: "Egito" },
    { label: "El Salvador", value: "El Salvador" },
    { label: "Emirados Árabes Unidos", value: "Emirados Arabes Unidos" },
    { label: "Equador", value: "Equador" },
    { label: "Eritreia", value: "Eritreia" },
    { label: "Eslováquia", value: "Eslovaquia" },
    { label: "Eslovênia", value: "Eslovenia" },
    { label: "Espanha", value: "Espanha" },
    { label: "Estados Unidos", value: "Estados Unidos" },
    { label: "Estônia", value: "Estonia" },
    { label: "Eswatini", value: "Eswatini" },
    { label: "Etiópia", value: "Etiopia" },
    { label: "Fiji", value: "Fiji" },
    { label: "Filipinas", value: "Filipinas" },
    { label: "Finlândia", value: "Finlandia" },
    { label: "França", value: "Franca" },
    { label: "Gabão", value: "Gabao" },
    { label: "Gâmbia", value: "Gambia" },
    { label: "Gana", value: "Gana" },
    { label: "Geórgia", value: "Georgia" },
    { label: "Granada", value: "Granada" },
    { label: "Grécia", value: "Grecia" },
    { label: "Guatemala", value: "Guatemala" },
    { label: "Guiana", value: "Guiana" },
    { label: "Guiné", value: "Guine" },
    { label: "Guiné Equatorial", value: "Guine Equatorial" },
    { label: "Guiné-Bissau", value: "Guine-Bissau" },
    { label: "Haiti", value: "Haiti" },
    { label: "Holanda", value: "Holanda" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hungria", value: "Hungria" },
    { label: "Iêmen", value: "Iemen" },
    { label: "Ilhas Marshall", value: "Ilhas Marshall" },
    { label: "Ilhas Salomão", value: "Ilhas Salomao" },
    { label: "Índia", value: "India" },
    { label: "Indonésia", value: "Indonesia" },
    { label: "Irã", value: "Ira" },
    { label: "Iraque", value: "Iraque" },
    { label: "Irlanda", value: "Irlanda" },
    { label: "Islândia", value: "Islandia" },
    { label: "Israel", value: "Israel" },
    { label: "Itália", value: "Italia" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japão", value: "Japao" },
    { label: "Jordânia", value: "Jordania" },
    { label: "Kiribati", value: "Kiribati" },
    { label: "Kuwait", value: "Kuwait" },
    { label: "Laos", value: "Laos" },
    { label: "Lesoto", value: "Lesoto" },
    { label: "Letônia", value: "Letonia" },
    { label: "Líbano", value: "Libano" },
    { label: "Libéria", value: "Liberia" },
    { label: "Líbia", value: "Libia" },
    { label: "Liechtenstein", value: "Liechtenstein" },
    { label: "Lituânia", value: "Lituania" },
    { label: "Luxemburgo", value: "Luxemburgo" },
    { label: "Macedônia do Norte", value: "Macedonia do Norte" },
    { label: "Madagascar", value: "Madagascar" },
    { label: "Malásia", value: "Malasia" },
    { label: "Malawi", value: "Malawi" },
    { label: "Maldivas", value: "Maldivas" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Marrocos", value: "Marrocos" },
    { label: "Maurício", value: "Mauricio" },
    { label: "Mauritânia", value: "Mauritania" },
    { label: "México", value: "Mexico" },
    { label: "Mianmar", value: "Mianmar" },
    { label: "Micronésia", value: "Micronesia" },
    { label: "Moçambique", value: "Mocambique" },
    { label: "Moldávia", value: "Moldavia" },
    { label: "Mônaco", value: "Monaco" },
    { label: "Mongólia", value: "Mongolia" },
    { label: "Montenegro", value: "Montenegro" },
    { label: "Namíbia", value: "Namibia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Nicarágua", value: "Nicaragua" },
    { label: "Níger", value: "Niger" },
    { label: "Nigéria", value: "Nigeria" },
    { label: "Noruega", value: "Noruega" },
    { label: "Nova Zelândia", value: "Nova Zelandia" },
    { label: "Omã", value: "Oma" },
    { label: "Palau", value: "Palau" },
    { label: "Palestina", value: "Palestina" },
    { label: "Panamá", value: "Panama" },
    { label: "Papua Nova Guiné", value: "Papua Nova Guine" },
    { label: "Paquistão", value: "Paquistao" },
    { label: "Paraguai", value: "Paraguai" },
    { label: "Peru", value: "Peru" },
    { label: "Polônia", value: "Polonia" },
    { label: "Portugal", value: "Portugal" },
    { label: "Quênia", value: "Quenia" },
    { label: "Quirguistão", value: "Quirguistao" },
    { label: "Reino Unido", value: "Reino Unido" },
    { label: "República Centro-Africana", value: "Republica Centro-Africana" },
    { label: "República Dominicana", value: "Republica Dominicana" },
    { label: "República Checa", value: "Republica Checa" },
    { label: "Romênia", value: "Romenia" },
    { label: "Ruanda", value: "Ruanda" },
    { label: "Rússia", value: "Russia" },
    { label: "Santa Sé (Vaticano)", value: "Santa Se (Vaticano)" },
    { label: "Samoa", value: "Samoa" },
    { label: "Santa Lúcia", value: "Santa Lucia" },
    { label: "São Cristóvão e Névis", value: "Sao Cristovao e Nevis" },
    { label: "São Marinho", value: "Sao Marinho" },
    { label: "São Tomé e Príncipe", value: "Sao Tome e Principe" },
    { label: "São Vicente e Granadinas", value: "Sao Vicente e Granadinas" },
    { label: "Seicheles", value: "Seicheles" },
    { label: "Senegal", value: "Senegal" },
    { label: "Serra Leoa", value: "Serra Leoa" },
    { label: "Sérvia", value: "Servia" },
    { label: "Singapura", value: "Singapura" },
    { label: "Síria", value: "Siria" },
    { label: "Somália", value: "Somalia" },
    { label: "Sri Lanka", value: "Sri Lanka" },
    { label: "Sudão", value: "Sudao" },
    { label: "Sudão do Sul", value: "Sudao do Sul" },
    { label: "Suécia", value: "Suecia" },
    { label: "Suíça", value: "Suica" },
    { label: "Suriname", value: "Suriname" },
    { label: "Tailândia", value: "Tailandia" },
    { label: "Tajiquistão", value: "Tajiquistao" },
    { label: "Tanzânia", value: "Tanzania" },
    { label: "Timor-Leste", value: "Timor-Leste" },
    { label: "Togo", value: "Togo" },
    { label: "Tonga", value: "Tonga" },
    { label: "Trinidad e Tobago", value: "Trinidad e Tobago" },
    { label: "Tunísia", value: "Tunisia" },
    { label: "Turcomenistão", value: "Turcomenistao" },
    { label: "Turquia", value: "Turquia" },
    { label: "Tuvalu", value: "Tuvalu" },
    { label: "Ucrânia", value: "Ucrania" },
    { label: "Uganda", value: "Uganda" },
    { label: "Uruguai", value: "Uruguai" },
    { label: "Uzbequistão", value: "Uzbequistao" },
    { label: "Vanuatu", value: "Vanuatu" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Vietnã", value: "Vietna" },
    { label: "Zâmbia", value: "Zambia" },
    { label: "Zimbábue", value: "Zimbabue" },
] as const

export type Country = typeof countries[number]["value"]
